"use strict";
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),os=require('os');
const {install,uninstall}=require('../src/install.cjs'),{collect}=require('../src/client.cjs'),{dispatch}=require('../src/receipts.cjs');
function temp(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'apick-package-test-'));t.after(()=>{const root=path.resolve(dir);if(root.startsWith(path.resolve(os.tmpdir())+path.sep)&&path.basename(root).startsWith('apick-package-test-'))fs.rmSync(root,{recursive:true,force:true});});return dir;}
test('설치·재설치·제거가 다른 설정과 수정된 스킬을 보존한다',t=>{const home=temp(t);fs.mkdirSync(path.join(home,'.codex'));fs.writeFileSync(path.join(home,'.codex/config.toml'),'model = "keep-model"\n[mcp_servers.existing]\ncommand = "keep"\n');fs.writeFileSync(path.join(home,'.claude.json'),JSON.stringify({theme:'keep',mcpServers:{existing:{command:'keep'}}}));install({home});install({home});const skill=path.join(home,'.agents/skills/apick-subagent/SKILL.md');fs.appendFileSync(skill,'\n사용자 메모');const result=uninstall({home});assert.ok(result.preserved.includes(skill));assert.match(fs.readFileSync(path.join(home,'.codex/config.toml'),'utf8'),/keep-model/);assert.doesNotMatch(fs.readFileSync(path.join(home,'.codex/config.toml'),'utf8'),/mcp_servers.apick_subagent/);assert.equal(JSON.parse(fs.readFileSync(path.join(home,'.claude.json'),'utf8')).mcpServers.existing.command,'keep');});
test('소유하지 않은 연결 설정을 덮어쓰지 않는다',t=>{const home=temp(t);fs.mkdirSync(path.join(home,'.codex'));fs.writeFileSync(path.join(home,'.codex/config.toml'),'[mcp_servers.apick_subagent]\ncommand="mine"');assert.throws(()=>install({home}));assert.match(fs.readFileSync(path.join(home,'.codex/config.toml'),'utf8'),/mine/);});
test('경로 탈출과 비밀 파일을 제외한다',t=>{const root=temp(t);fs.writeFileSync(path.join(root,'safe.md'),'공개 문서');fs.writeFileSync(path.join(root,'.env'),'비공개');fs.writeFileSync(path.join(root,'settings.json'),'비공개');fs.writeFileSync(path.join(root,'config.production.yaml'),'비공개');assert.deepEqual(collect(root,['*']).map(x=>x.path),['safe.md']);assert.throws(()=>collect(root,['../*']));});
test('내용 속 인증정보와 링크를 전송하지 않는다',t=>{const root=temp(t);fs.writeFileSync(path.join(root,'data.md'),'-----BEGIN ENCRYPTED PRIVATE KEY-----');assert.throws(()=>collect(root,['data.md']));fs.writeFileSync(path.join(root,'data.md'),'password="abcdefghijklmnop012345"');assert.throws(()=>collect(root,['data.md']));});
test('응답 유실 후 저장 안 함 요청도 동일 파일 ID로 재접수한다',async t=>{const root=temp(t),list=[{path:'a.md',bytes:Buffer.from('자료')}];let uploads=0,calls=0,bodies=[];const client={scope:'fixture',upload:async()=>({file_id:'f'+ ++uploads}),request:async(method,route,body)=>{if(method==='GET')return {job_id:'saj_fixture'};bodies.push(body);if(++calls===1)throw Error('응답 유실');return {job_id:'saj_fixture'};}};const args={kind:'extract',goal:'근거 추출',include:['a.md'],retention:'none',idempotency_key:'fixed-request'};await assert.rejects(dispatch(client,root,args,list,{home:root}));await dispatch(client,root,args,list,{home:root});assert.equal(uploads,1);assert.deepEqual(bodies[0],bodies[1]);await assert.rejects(dispatch(client,root,{...args,goal:'변경'},list,{home:root}),{code:'IDEMPOTENCY_CONFLICT'});});
test('접수 전 취소는 유료 작업을 만들지 않는다',async t=>{const root=temp(t),abort=new AbortController();let submitted=false;const client={scope:'fixture',upload:async()=>{abort.abort();return {file_id:'f1'};},request:async()=>{submitted=true;}};await assert.rejects(dispatch(client,root,{kind:'extract',goal:'추출',idempotency_key:'cancelled'},[{path:'a.md',bytes:Buffer.from('자료')}],{home:root,signal:abort.signal}));assert.equal(submitted,false);});
test('잘못된 JSON-RPC 메시지는 브리지를 종료하지 않는다',async()=>{const {spawn}=require('child_process');const child=spawn(process.execPath,[path.resolve(__dirname,'../src/cli.cjs'),'mcp'],{stdio:['pipe','pipe','pipe']});let output='';child.stdout.on('data',d=>output+=d);child.stdin.end('null\n'+JSON.stringify({jsonrpc:'2.0',id:1,method:'ping'})+'\n');const exit=await new Promise(r=>child.once('exit',r));assert.equal(exit,0);assert.match(output,/-32600/);assert.match(output,/"id":1,"result":\{\}/);});
